#ifndef QSCRIPTENGINE_QSCRIPTENGINEAGENT_H
#define QSCRIPTENGINE_QSCRIPTENGINEAGENT_H

#include <QString>
#include <QMap>
#include <QObject>

class QScriptEngine;
class QScriptContext;
class QScriptValue;

class QScriptEngineAgent
{
public:

    explicit QScriptEngineAgent(QScriptEngine *engine = nullptr);
    virtual ~QScriptEngineAgent();

    virtual void contextPop();
    virtual void contextPush();
    QScriptEngine *engine() const;
    virtual void exceptionCatch(qint64 scriptId, const QScriptValue &exception);
    virtual void exceptionThrow(qint64 scriptId, const QScriptValue &exception, bool hasHandler);
    // virtual QVariant extension(QScriptEngineAgent::Extension extension, const QVariant &argument = QVariant());
    virtual void functionEntry(qint64 scriptId);
    virtual void functionExit(qint64 scriptId, const QScriptValue &returnValue);
    virtual void positionChange(qint64 scriptId, int lineNumber, int columnNumber);
    virtual void scriptLoad(qint64 id, const QString &program, const QString &fileName, int baseLineNumber);
    virtual void scriptUnload(qint64 id);
    // virtual bool supportsExtension(QScriptEngineAgent::Extension extension) const;


    // 以下接口内部使用，外部不要使用
    bool isPosChanged(qint64 line, qint64 col);
    qint64 scriptId(QString fileName);

private:
    QScriptEngine *m_engine{nullptr};

    qint64 mLastLine;
    qint64 mLastCol;
};

class QJDefines: public QObject
{
    Q_OBJECT

public:
    enum OPCodeEnum {
        OP_invalid = 0,
        OP_push_i32 = 1,
        OP_push_const = 2,
        OP_fclosure = 3,
        OP_push_atom_value = 4,
        OP_private_symbol = 5,
        OP_undefined = 6,
        OP_null = 7,
        OP_push_this = 8,
        OP_push_false = 9,
        OP_push_true = 10,
        OP_object = 11,
        OP_special_object = 12,
        OP_rest = 13,
        OP_drop = 14,
        OP_nip = 15,
        OP_nip1 = 16,
        OP_dup = 17,
        OP_dup1 = 18,
        OP_dup2 = 19,
        OP_dup3 = 20,
        OP_insert2 = 21,
        OP_insert3 = 22,
        OP_insert4 = 23,
        OP_perm3 = 24,
        OP_perm4 = 25,
        OP_perm5 = 26,
        OP_swap = 27,
        OP_swap2 = 28,
        OP_rot3l = 29,
        OP_rot3r = 30,
        OP_rot4l = 31,
        OP_rot5l = 32,
        OP_call_constructor = 33,
        OP_call = 34,
        OP_tail_call = 35,
        OP_call_method = 36,
        OP_tail_call_method = 37,
        OP_array_from = 38,
        OP_apply = 39,
        OP_return = 40,
        OP_return_undef = 41,
        OP_check_ctor_return = 42,
        OP_check_ctor = 43,
        OP_init_ctor = 44,
        OP_check_brand = 45,
        OP_add_brand = 46,
        OP_return_async = 47,
        OP_throw = 48,
        OP_throw_error = 49,
        OP_eval = 50,
        OP_apply_eval = 51,
        OP_regexp = 52,
        OP_get_super = 53,
        OP_import = 54,
        OP_check_var = 55,
        OP_get_var_undef = 56,
        OP_get_var = 57,
        OP_put_var = 58,
        OP_put_var_init = 59,
        OP_put_var_strict = 60,
        OP_get_ref_value = 61,
        OP_put_ref_value = 62,
        OP_define_var = 63,
        OP_check_define_var = 64,
        OP_define_func = 65,
        OP_get_field = 66,
        OP_get_field2 = 67,
        OP_put_field = 68,
        OP_get_private_field = 69,
        OP_put_private_field = 70,
        OP_define_private_field = 71,
        OP_get_array_el = 72,
        OP_get_array_el2 = 73,
        OP_put_array_el = 74,
        OP_get_super_value = 75,
        OP_put_super_value = 76,
        OP_define_field = 77,
        OP_set_name = 78,
        OP_set_name_computed = 79,
        OP_set_proto = 80,
        OP_set_home_object = 81,
        OP_define_array_el = 82,
        OP_append = 83,
        OP_copy_data_properties = 84,
        OP_define_method = 85,
        OP_define_method_computed = 86,
        OP_define_class = 87,
        OP_define_class_computed = 88,
        OP_get_loc = 89,
        OP_put_loc = 90,
        OP_set_loc = 91,
        OP_get_arg = 92,
        OP_put_arg = 93,
        OP_set_arg = 94,
        OP_get_var_ref = 95,
        OP_put_var_ref = 96,
        OP_set_var_ref = 97,
        OP_set_loc_uninitialized = 98,
        OP_get_loc_check = 99,
        OP_put_loc_check = 100,
        OP_put_loc_check_init = 101,
        OP_get_var_ref_check = 102,
        OP_put_var_ref_check = 103,
        OP_put_var_ref_check_init = 104,
        OP_close_loc = 105,
        OP_if_false = 106,
        OP_if_true = 107,
        OP_goto = 108,
        OP_catch = 109,
        OP_gosub = 110,
        OP_ret = 111,
        OP_nip_catch = 112,
        OP_to_object = 113,
        OP_to_propkey = 114,
        OP_to_propkey2 = 115,
        OP_with_get_var = 116,
        OP_with_put_var = 117,
        OP_with_delete_var = 118,
        OP_with_make_ref = 119,
        OP_with_get_ref = 120,
        OP_with_get_ref_undef = 121,
        OP_make_loc_ref = 122,
        OP_make_arg_ref = 123,
        OP_make_var_ref_ref = 124,
        OP_make_var_ref = 125,
        OP_for_in_start = 126,
        OP_for_of_start = 127,
        OP_for_await_of_start = 128,
        OP_for_in_next = 129,
        OP_for_of_next = 130,
        OP_iterator_check_object = 131,
        OP_iterator_get_value_done = 132,
        OP_iterator_close = 133,
        OP_iterator_next = 134,
        OP_iterator_call = 135,
        OP_initial_yield = 136,
        OP_yield = 137,
        OP_yield_star = 138,
        OP_async_yield_star = 139,
        OP_await = 140,
        OP_neg = 141,
        OP_plus = 142,
        OP_dec = 143,
        OP_inc = 144,
        OP_post_dec = 145,
        OP_post_inc = 146,
        OP_dec_loc = 147,
        OP_inc_loc = 148,
        OP_add_loc = 149,
        OP_not = 150,
        OP_lnot = 151,
        OP_typeof = 152,
        OP_delete = 153,
        OP_delete_var = 154,
        OP_mul = 155,
        OP_div = 156,
        OP_mod = 157,
        OP_add = 158,
        OP_sub = 159,
        OP_shl = 160,
        OP_sar = 161,
        OP_shr = 162,
        OP_and = 163,
        OP_xor = 164,
        OP_or = 165,
        OP_pow = 166,
        OP_lt = 167,
        OP_lte = 168,
        OP_gt = 169,
        OP_gte = 170,
        OP_instanceof = 171,
        OP_in = 172,
        OP_eq = 173,
        OP_neq = 174,
        OP_strict_eq = 175,
        OP_strict_neq = 176,
        OP_is_undefined_or_null = 177,
        OP_private_in = 178,
        OP_push_bigint_i32 = 179,
        OP_nop = 180,
        OP_enter_scope = 181,
        OP_leave_scope = 182,
        OP_label = 183,
        OP_scope_get_var_undef = 184,
        OP_scope_get_var = 185,
        OP_scope_put_var = 186,
        OP_scope_delete_var = 187,
        OP_scope_make_ref = 188,
        OP_scope_get_ref = 189,
        OP_scope_put_var_init = 190,
        OP_scope_get_private_field = 191,
        OP_scope_get_private_field2 = 192,
        OP_scope_put_private_field = 193,
        OP_scope_in_private_field = 194,
        OP_get_field_opt_chain = 195,
        OP_get_array_el_opt_chain = 196,
        OP_set_class_name = 197,
        OP_source_loc = 198,
        OP_push_minus1 = 199,
        OP_push_0 = 200,
        OP_push_1 = 201,
        OP_push_2 = 202,
        OP_push_3 = 203,
        OP_push_4 = 204,
        OP_push_5 = 205,
        OP_push_6 = 206,
        OP_push_7 = 207,
        OP_push_i8 = 208,
        OP_push_i16 = 209,
        OP_push_const8 = 210,
        OP_fclosure8 = 211,
        OP_push_empty_string = 212,
        OP_get_loc8 = 213,
        OP_put_loc8 = 214,
        OP_set_loc8 = 215,
        OP_get_loc0_loc1 = 216,
        OP_get_loc0 = 217,
        OP_get_loc1 = 218,
        OP_get_loc2 = 219,
        OP_get_loc3 = 220,
        OP_put_loc0 = 221,
        OP_put_loc1 = 222,
        OP_put_loc2 = 223,
        OP_put_loc3 = 224,
        OP_set_loc0 = 225,
        OP_set_loc1 = 226,
        OP_set_loc2 = 227,
        OP_set_loc3 = 228,
        OP_get_arg0 = 229,
        OP_get_arg1 = 230,
        OP_get_arg2 = 231,
        OP_get_arg3 = 232,
        OP_put_arg0 = 233,
        OP_put_arg1 = 234,
        OP_put_arg2 = 235,
        OP_put_arg3 = 236,
        OP_set_arg0 = 237,
        OP_set_arg1 = 238,
        OP_set_arg2 = 239,
        OP_set_arg3 = 240,
        OP_get_var_ref0 = 241,
        OP_get_var_ref1 = 242,
        OP_get_var_ref2 = 243,
        OP_get_var_ref3 = 244,
        OP_put_var_ref0 = 245,
        OP_put_var_ref1 = 246,
        OP_put_var_ref2 = 247,
        OP_put_var_ref3 = 248,
        OP_set_var_ref0 = 249,
        OP_set_var_ref1 = 250,
        OP_set_var_ref2 = 251,
        OP_set_var_ref3 = 252,
        OP_get_length = 253,
        OP_if_false8 = 254,
        OP_if_true8 = 255,
        OP_goto8 = 256,
        OP_goto16 = 257,
        OP_call0 = 258,
        OP_call1 = 259,
        OP_call2 = 260,
        OP_call3 = 261,
        OP_is_undefined = 262,
        OP_is_null = 263,
        OP_typeof_is_undefined = 264,
        OP_typeof_is_function = 265
    };
    Q_ENUM(OPCodeEnum)

    explicit QJDefines(QObject *parent = nullptr) :
        QObject(parent)
    {

    }

};

#endif // QSCRIPTENGINE_QSCRIPTENGINEAGENT_H

